---
title: "CV comune"
date: 2023-06-29T12:00:00+02:00
createdDate: 2023-06-12T12:00:00+02:00
url: "/cv/comune/"
layout: cv_comune
---
// Infine: rendere i due div responsive: https://www.w3schools.com/html/html_responsive.asp

== Esperienze lavorative
  * link:/cv/informatico/#icranet[*Manutentore di rete*, title=Dettagli] presso ICRANet Pescara per conto di mailto:damiano.verzulli@soabit.com[Soabit s.r.l., title="Damiano Verzulli"] (09/01/2023 - 30/06/2023).
  * link:/cv/informatico/#iasait[*Webmaster*, title=Dettagli] per l'A.S.D. mailto:segreteria@iasa-italia.it[IASA Italia, title="Segreteria IASA Italia"] (_sine data_, 2016 - 2021).

== Progetti personali
  * Realizzazione del link:/[sito personale] che state visitando con Hugo (giugno 2023 - in corso).
  * Realizzazione prototipo nuovo sito per l'org. ICRANet con Hugo (maggio 2023 - in corso, sospeso).
  * Progettazione trasmissione, assi/alberi e supporti di una ipotetica pressa meccanica a doppio eccentrico per l'esame di Costruzione di Macchine.

== Istruzione
  * (Iscritto al Corso di) Laurea Triennale in Ingegneria Meccanica presso l'Università degli Studi di Salerno - CFU conseguiti 150/180 (83.3%).
  * Diploma di Istruzione Superiore conseguito presso il Liceo Scientifico Margherita Hack, Baronissi SA (ex IIS Baronissi) - voto di maturità 96/100.

=== Lingue parlate
  * Italiano - madrelingua
  * Inglese - livello Cambridge B2

=== Corsi di formazione (attestati)
  * "*DIGITAL MANUFACTURING - Prototipazione 3D e CNC*" (giugno 2021 - agosto 2021) - cod. prog. Formatemp "094 PROT D211 1983".
  * "*Corso di Formazione Generale per i Lavoratori*" (luglio 2021) - cod. att. (link:https://opnitalialavoro.it/verifica-dellautenticita/[137413_5/15, title="Verifica autenticità", window=_blank]).

=== Certificazioni
==== Lingua inglese
  * "*Certificazione _Cambridge English First_, Level B2*" (luglio 2016) - cert. num. 0053909676.
    ** Esame di verifica conseguito in data 22/07/2016 e superato con voto finale di *174 - Grade B*.

== Capacità principali
=== Hard skill
  * #Disegno tecnico industriale#
    ** *Disegno tecnico*: capacità di lettura dei disegni, conoscenza delle normative ISO riguardanti messa in tavola e quotatura, capacità di utilizzo degli strumenti di misura.
    ** *Software*: buone capacità con *AutoCAD*, *nanoCAD*, *Catia V5*, *Solidworks 2020*; conoscenze di base di *FreeCAD* e *Ansys*.
      *** So realizzare parti e assiemi di modelli 3D, so fare analisi cinematiche del moto via Catia e Solidworks e ho conoscenze di base circa le analisi delle tensioni meccaniche con il F.E.M.

  * #link:/cv/informatico/#hardskill[Informatica]#
    ** *Sistemi operativi*: utente avanzato di S.O. Windows e di varie distribuzioni Linux; dimestichezza con interfacce a riga di comando (CLI), in particolare Bash; dimestichezza con systemd ed esperienze minori con altri init daemon.
    ** *Database*: conoscenza di base dell'algebra relazionale; conoscenza del linguaggio SQL.
    ** *Linguaggi di programmazione*: esperienze di programmazione con MATLAB, Python 3, LabVIEW e Bash; conoscenza di base di GNU Octave, C e Javascript.
    ** *Web development*: buona conoscenza di HTML5, CSS3 e SCSS per front-end web development; conoscenza di base del CMS Hugo; esperienza con il CMS Wordpress.

// Devo caricare da qualche parte il mio PdS e poi linkarlo qui
  * #link:/cv/ingegnere/#hardskill[Ingegneria meccanica]#
    ** Conoscenze di ingegneria meccanica, ovvero: matematica I e II, fisica generale, chimica inorganica; tecnologia generale dei materiali e tecnologia meccanica, disegno tecnico industriale e grafica computazionale tecnica; meccanica razionale, scienza delle costruzioni, meccanica applicata e costruzione di macchine; termodinamica e trasmissione del calore, macchine e sistemi energetici, meccanica dei fluidi e impianti di condizionamento; economia e organizzazione aziendale, progettazione e gestione degli impianti industriali; elettrotecnica, fondamenti di informatica e sistemi di misura per l'industria 4.0.
    ** Per ulteriori dettagli, consultare la pagina dedicata al link:/cv/ingegnere#cdl[curriculum come ingegnere meccanico].

  * #Progettazione meccanica#
    ** *CNC*: conoscenza di base del linguaggio G-code, uso del software CIMCO Edit.
    ** *Tolleranze*: conoscenza delle tolleranze geometriche e dimensionali, conoscenza della rugosità e della sua influenza sul moto relativo tra componenti in contatto.
    ** *Materiali metallici*: conoscenza delle proprietà meccaniche dei mat. metallici, delle lavorazioni e dei trattamenti termici e di rifinitura più comuni.
    ** *Prototipazione rapida*: nozioni sul funzionamento della stampa 3D (FDM, SLA).

  * #Software da ufficio e documentale#
    ** Competenza con i programmi dei *pacchetti MS Office*, *LibreOffice* e *Google Docs Editor*.
    ** *Stesura documentazione*: "parlo bene" LaTeX, Markdown e Asciidoctor - con il primo sto scrivendo la tesi di laurea, con gli altri questo sito documentale; ho familiarità con reStructuredText; naturalmente, so usare MS Word, LibreOffice Writer e Google Docs.
    ** *Video editing*: esperienze di editing con Kdenlive; competenza con OBS, conoscenza di base di Vegas (ex. Sony Vegas).

=== Soft skill
[cols=3]
|===
|Precisione:
|
|★★★★★

|Problem solving:
|
|★★★★★

|Pazienza:
|
|★★★★☆

|Pianificazione:
|
|★★★★☆

|Rapporti interpersonali:
|
|★★★★☆

|Lavoro di squadra:
|
|★★★★☆

|Saper ascoltare:
|
|★★★☆☆

|Autonomia:
|
|★★☆☆☆
|===
