---
title: "CV come Ingegnere Meccanico"
date: 2023-06-14T12:00:00+02:00
createdDate: 2023-06-12T12:00:00+02:00
layout: single
---

== Istruzione
=== Iscritto al _Corso di Laurea Triennale in Ingegneria Meccanica_ presso l'Università degli Studi di Salerno
* Immatricolato nell'A.A. 2017/2018, attualmente iscritto al 3° anno (3° FC).
* CFU conseguiti: 150/180 (83.3%).
* Esami registrati: 19/23. Media ponderata: 24.664/30
* Conoscenze acquisite dal CdL (in estrema sintesi):
  ** *Matematica e fisica*: funzioni elementari, num. complessi, analisi/studio della funzione - il che include derivate, limiti e integrali definiti o indefiniti; analisi su più variabili indipendenti, eq. differenziali fino al secondo ordine, integrali doppi e tripli, derivate parziali; vettori e matrici, rango/immagine/kernel/determinante etc., operazioni elementari; fisica generale, meccanica del punto materiale, di distribuzioni discrete di punti e del corpo rigido; moto rotativo e delle grandezze studiate in tale ambito (mom. d'inerzia, coppia, mom. angolare etc.); forze d'attrito; elettromagnetismo; meccanica del corpo rigido, fondamenti di algebra vettoriale, meccanica newtoniana e dalambertiana.
  ** *Tecnologia dei materiali*: classificazione dei materiali, principali configurazioni molecolari dei mat. metallici, trattamenti termici più importanti, diagrammi di stato (incl. _diagramma Ferro-Carbonio_), prove di resistenza (rottura, durezza, resilienza) sui metalli; lavorazioni per deformazione plastica a caldo e a freddo, lavorazioni per asportazione di truciolo, saldature, fonderia.
  ** *Scienza delle costruzioni e costruzione di macchine*: meccanica del corpo continuo, tensioni nel c.c., teoria tecnica della trave, statica della trave, principio di De Saint-Venant e criteri di resistenza; resistenza e verifica di strutture sottili tridimensionali, serbatoi a parete sottile, meccanica della frattura, fatica nei materiali, organi di macchine.
  ** *Termodinamica applicata*: leggi della termodinamica e applicazioni delle suddette nei sistemi aperti e chiusi, elementi degli impianti di produzione di energia; trasmissione del calore per conduzione, convezione e irraggiamento; meccanica dei fluidi, accenni di aerodinamica e idraulica; principali tipologie di sistemi energetici (impianti a vapore, a gas, nucleari, idroelettrici, motori a combustione interna), termofluidodinamica delle macchine, classificazione delle macchine, turbine e compressori; aria umida, involucro edilizio, impianti di condizionamento dell'aria con relative normative, sistemi di produzione idronici, C.T.A., generatori di calore, macchine a compressione di vapore, refrigeratori ad assorbimento.
  ** *Progettazione e gestione degli impianti industriali*: indici di prestazione di un impianto, studio e progettazione del layout di impianto, colli di bottiglia, simulazioni e metodo Montecarlo, contabilità industriale, gestione delle scorte in magazzino, distinta base, approvvigionamenti, tempi e metodi, manutenzione.
  ** *Elettrotecnica*: elementi fondamentali di un circuito elettrico, corrente DC e AC, corrente AC monofase, bifase e trifase, leggi di Ohm e Kirchhoff, circuiti equivalenti Thevenin e Norton, rifasamento di un impianto trifase, trasformatori ideali, circuiti in evoluzione dinamica (RC, RL, RLC), accenni di motori elettrici, accenni di elettronica.
  ** *Disegno tecnico*: capacità di lettura dei disegni, normative ISO riguardanti messa in tavola e quotatura, tolleranze geometriche e dimensionali, rugosità e sua influenza sul moto relativo tra componenti in contatto, uso del software _AutoCAD_; fondamenti di grafica computazionale, curve e superfici, modellazione matematica di un oggetto, uso del software _Solidworks_.
  ** *Altro*: organigramma aziendale, bilancio di esercizio, meccanica applicata alle macchine, sistemi di misura per l'industria 4.0, uso del software _LabVIEW_, fondamenti di chimica inorganica, fondamenti di informatica, uso del linguaggio/software _Matlab_, accenni di database, algebra relazionale e linguaggio _MySQL_.
